spring.application.name=tech_nova

server.port=8084

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/tech_nova?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update

